CREATE DATABASE IF NOT EXISTS SAFEHOUSEPUP;
CREATE SCHEMA IF NOT EXISTS SAFEHOUSEPUP;

USE SAFEHOUSEPUP;

CREATE TABLE USER_INFO(
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) UNIQUE NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR (50) NOT NULL,
    Address VARCHAR(250) NOT NULL,
    Email VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Safe_Houses (
    SafeHouseID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    SafeHouseName VARCHAR(50) NOT NULL,
    Location VARCHAR(250) NOT NULL,
    ContactNumber int(11) NOT NULL,
    Status BOOLEAN NOT NULL
);
CREATE TABLE ROOMTYPE (
	ROOMTYPE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ROOMTYPE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE Rooms (
    RoomID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ROOMTYPE_ID INT NOT NULL,
    RoomName VARCHAR(50) NOT NULL,
    SafeHouseID INT NOT NULL,
    CAPACITY INT NOT NULL DEFAULT 200,
    FOREIGN KEY (SafeHouseID) REFERENCES Safe_Houses(SafeHouseID),
    FOREIGN KEY (ROOMTYPE_ID) REFERENCES ROOMTYPE(ROOMTYPE_ID)
);

CREATE TABLE AssignedSafehouseandRooms (
    AssignmentID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    UserID INT NOT NULL,
    RoomID INT NOT NULL,
    Current_STATUS BOOLEAN NOT NULL,
    AssignedTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID),
    FOREIGN KEY (RoomID) REFERENCES Rooms(RoomID)
);

CREATE TABLE BARANGGAY_STAFF (
	STAFFID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Username VARCHAR(50) UNIQUE NOT NULL,
	FIRSTNAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR (50) NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	Password VARCHAR(255) NOT NULL
);

